"""Create Test User

Revision ID: 45cd7dee0ca
Revises: 4e6ec61d9cb
Create Date: 2019-03-21 15:05:08.457627

"""

# revision identifiers, used by Alembic.
revision = '45cd7dee0ca'
down_revision = '4e6ec61d9cb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('telegram_notification', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_account'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_notification')
    op.drop_column('users', 'tags')
    ### end Alembic commands ###
